set pages 10000 lines 10000 trims on
col PROJECT_ID for a10
col PROJECT_NAME for a12
col END_USER for a8
col START_DATE for a10
col RELEASE_DATE for a12
col PROJECT_STATUS for a14
col MEMBER_NAME for a11
col MEMBER_AGE for a10
col ENTRYDATE for a10
col FAVORITE_FOOD for a20

SELECT
  PRO.PROJECT_ID,
  PRO.PROJECT_NAME,
  EU.END_USER_NAME AS END_USER,
  TO_CHAR(PRO.START_DATE,'YYYY/MM/DD') AS START_DATE,
  TO_CHAR(PRO.RELEASE_DATE, 'YYYY/MM/DD') AS RELEASE_DATE,
  CASE
    WHEN PRO.PROJECT_STATUS = 0 THEN '保守'
    ELSE '開発'
  END AS PROJECT_STATUS,
  MEM.MEMBER_NAME,
  TO_CHAR(
    EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM MEM.BIRTHDAY) -
      CASE
        WHEN TO_CHAR(SYSDATE, 'MMDD') < TO_CHAR(MEM.BIRTHDAY, 'MMDD') THEN 1
        ELSE 0 
      END
  ) AS MEMBER_AGE,
  TO_CHAR(MEM.ENTRYDATE,'YYYY/MM/DD') AS ENTRYDATE,
  MEM.FAVORITE_FOOD
FROM
  MEMBER MEM
INNER JOIN
  J_PROJECT_MEMBER JPM
ON
  MEM.MEMBER_ID = JPM.MEMBER_ID
INNER JOIN
  PROJECT PRO
ON
  PRO.PROJECT_ID = JPM.PROJECT_ID
INNER JOIN
  END_USER EU
ON
  EU.END_USER_ID = PRO.END_USER_ID
;
